### ISSUE TITLE
Anna Tasks

### ISSUE THREAD

**Issue by donutfino** [TeamZoon/onemap_mobile_dev#50]
- [x] place stories - work more like feed items. only show published followings's stories, latest first, infinite load, sync
- [x] feed, recommended user - sync when followed/unfollow , hide label when no recommended
- [x] feed, place story item - display bookmark item
- [x] collections, setting private, public collection
- [x] collections, collection cover picture
- [x] place, default check in rules (user able to checking within x meters from location lat, long) and user can check in in x minute after last checked in, improve UI - disable (gray) while not able to check in
- [ ] place, campaign check in rules. almost the same as default checkin rules but read rules from campaign rules
- [x] collections, view followers collection (hide private collections)
- [ ] feed, add user followings activities notification (follow you, add/remove place to/from collection, hearted/like place, write/edit story)
- [ ] feed, partner campaign notification (new campaign, near to campaign places)
- [ ] place profile, create place profile manually

**Comment by redrose218** [comment]
3. on place story page, now bookmark is at the right-top corner(IMG_0610)
you mean show bookmarks for each story(IMG_0611)?
![img_0610](https://user-images.githubusercontent.com/34869395/36003531-2e3e5024-0d37-11e8-8bc1-036e5d0ba14e.PNG)
![img_0611](https://user-images.githubusercontent.com/34869395/36003532-2e695d14-0d37-11e8-8db0-e1cf83ba3265.PNG)
